### ISSUE TITLE
ERROR RUNNING PYFAT USING BASIC CONFIGURATION FILE

### ISSUE THREAD

**Issue by bnamumba** [PeterKamphuis/pyFAT-astro#14]
brenda@WKAPP-2024-03-12.sif:/scratch3/users/brenda/wlm2/MHONGOOSE$ pyFAT configuration_file = FAT_defaults.yml
This is version 0.1.3 of pyFAT.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/main.py", line 106, in main
    cfg_input = OmegaConf.merge(cfg,inputconf)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/omegaconf.py", line 273, in merge
    target.merge_with(*configs[1:])
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 432, in _map_merge
    dest[key] = src._get_node(key)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 310, in __setitem__
    self._format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 545, in _set_item_impl
    self._validate_set(key, value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 175, in _validate_set
    self._validate_non_optional(key, value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 245, in _validate_non_optional
    child = self._get_node(key)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigKeyError: Key '' not in 'defaults'
    full_key:
    object_type=defaults

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyFAT", line 10, in <module>
    main.main(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/main.py", line 294, in main
    raise ProgramError(f'''Something went wrong in the main. This should not happen. Please list an issue on github.''')
pyFAT_astro.Support.fat_errors.ProgramError: Something went wrong in the main. This should not happen. Please list an issue on github.

**Comment by PeterKamphuis** [comment]
Omega Conf does not like space so your call should be:
pyFAT configuration_file=FAT_defaults.yml

without the space around the =
