### ISSUE TITLE
This problem often occurs when I reboot my compute, but the pyFAT passed the test  'pyFAT installation_check=True'

### ISSUE THREAD

**Issue by liuxiaolan2018** [PeterKamphuis/pyFAT-astro#8]
File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/main.py", line 104, in main
    cfg_input = OmegaConf.merge(cfg,inputconf)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 264, in merge
    target.merge_with(*configs[1:])
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 452, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 738, in format_and_raise
    _raise(ex, cause)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 450, in merge_with
    self._merge_with(*others)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 474, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 392, in _map_merge
    dest[key] = src._get_node(key)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 310, in __setitem__
    self._format_and_raise(
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 738, in format_and_raise
    _raise(ex, cause)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 507, in _set_item_impl
    self._validate_set(key, value)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 176, in _validate_set
    self._validate_non_optional(key, value)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 246, in _validate_non_optional
    child = self._get_node(key)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 166, in _validate_get
    self._format_and_raise(
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 818, in format_and_raise
    _raise(ex, cause)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key '' not in 'defaults'
    full_key: 
    object_type=defaults

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxl/hifast_env/bin/pyFAT", line 7, in <module>
    main.main(sys.argv[1:])
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/main.py", line 414, in main
    Configuration['FINAL_COMMENT'] = e
UnboundLocalError: local variable 'Configuration' referenced before assignment

**Comment by liuxiaolan2018** [comment]
Thank you. The problem is solved. There is a ' ' in the cube_name I input.
